ANDROID: fix crashdump_defconfig menuconfig
aarch64 was hitting the following error, CONFIG_VMAP_STACK appears to be
forced on for arm64 now:

    ERROR: CONFIG_VMAP_STACK: actual 'y', expected '' from common/arch/arm64/configs/crashdump_defconfig

Similarly, x86_64 seems to require CONFIG_SPARSEMEM_VMEMMAP, probably
because of `ARCH_SELECT_MEMORY_MODEL=y` (on by default):

    ERROR: CONFIG_SPARSEMEM_VMEMMAP: actual 'y', expected '' from common/arch/x86/configs/crashdump_defconfig

Bug: 436349788
Test: build
Change-Id: I7c0617990c5e398d4568b724fdee5b460ca92228
Signed-off-by: Frederick Mayle <fmayle@google.com>